# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-05 01:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Running', 'Running'), ('Done', 'Done'), ('Error', 'Error'), ('Waiting', 'Waiting'), ('FAIL', 'FAIL'), ('PASS', 'PASS')], max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('job_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=250)),
                ('text', models.TextField(blank=True, null=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='proxy.Job')),
            ],
        ),
        migrations.CreateModel(
            name='Job_Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_sha', models.CharField(max_length=60)),
                ('project_branch', models.CharField(max_length=60)),
                ('testurl', models.CharField(max_length=250)),
                ('robot_parameter', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('pid', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('status', models.CharField(choices=[('Running', 'Running'), ('Done', 'Done'), ('Error', 'Error'), ('Waiting', 'Waiting'), ('FAIL', 'FAIL'), ('PASS', 'PASS')], max_length=20)),
                ('revision_number', models.CharField(blank=True, max_length=50, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proxy.Job')),
            ],
        ),
        migrations.CreateModel(
            name='Job_Test_Distributed_Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=250)),
                ('script', models.CharField(max_length=250)),
                ('log', models.TextField(blank=True, null=True)),
                ('log_path', models.CharField(max_length=250)),
                ('report', models.CharField(blank=True, max_length=250, null=True)),
                ('job_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proxy.Job_Test')),
            ],
        ),
        migrations.CreateModel(
            name='Job_Test_Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField(blank=True, null=True)),
                ('log_path', models.CharField(max_length=250)),
                ('report', models.CharField(blank=True, max_length=250, null=True)),
                ('job_test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='proxy.Job_Test')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('host', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Running', 'Running'), ('Done', 'Done'), ('Error', 'Error'), ('Waiting', 'Waiting'), ('FAIL', 'FAIL'), ('PASS', 'PASS')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Svn',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Test_Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=50)),
                ('test', models.CharField(max_length=50)),
                ('testurl', models.CharField(max_length=250)),
                ('robot_parameter', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('use', models.BooleanField(default=True)),
            ],
        ),
    ]
