# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-17 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='projects',
            field=models.ManyToManyField(to='proxy.Project'),
        ),
    ]
