# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-17 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0002_auto_20180717_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='aws_instance_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
