# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-07 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0005_auto_20180718_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='port',
            field=models.CharField(default='51234', max_length=50),
        ),
    ]
