# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-28 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0006_node_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_map',
            name='app',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
