# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-28 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0007_test_map_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_test',
            name='app',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
