# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-29 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0008_job_test_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='servers',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
